server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # 1. RUTA DE USUARIOS (El guardia de seguridad)
        - id: ms-usuarios-route
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/usuarios/**

        # 2. RUTA DE NECESIDADES
        - id: ms-necesidades-route
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/necesidades/**
          filters:
            - name: CircuitBreaker
              args:
                name: necesidadesCB
                fallbackUri: forward:/fallback/necesidades

        # 3. RUTA DE DONACIONES
        - id: ms-donaciones-route
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/donaciones/**
          filters:
            - name: CircuitBreaker
              args:
                name: donacionesCB
                fallbackUri: forward:/fallback/donaciones

        # 4. RUTA DE LOGISTICA
        - id: ms-logistica-route
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/logistica/**
          filters:
            - name: CircuitBreaker
              args:
                name: logisticaCB
                fallbackUri: forward:/fallback/logistica

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
    instances:
      necesidadesCB:
        baseConfig: default
      donacionesCB:
        baseConfig: default
      logisticaCB:
        baseConfig: default