server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ms-necesidades-route
          uri: http://ms-necesidades:8082
          predicates:
            - Path=/api/v1/necesidades/**
          filters:
            - name: CircuitBreaker
              args:
                name: necesidadesCB
                fallbackUri: forward:/fallback/necesidades

        - id: ms-donaciones-route
          uri: http://ms-donaciones:8083
          predicates:
            - Path=/api/v1/donaciones/**
          filters:
            - name: CircuitBreaker
              args:
                name: donacionesCB
                fallbackUri: forward:/fallback/donaciones

        - id: ms-logistica-route
          uri: http://ms-logistica:8084
          predicates:
            - Path=/api/v1/logistica/**
        - id: ms-usuarios
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/usuarios/**

          filters:
            - name: CircuitBreaker
              args:
                name: logisticaCB
                fallbackUri: forward:/fallback/logistica

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
    instances:
      necesidadesCB:
        baseConfig: default
      donacionesCB:
        baseConfig: default
      logisticaCB:
        baseConfig: default
